# Generated by Django 2.2.5 on 2020-03-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=255, unique=True)),
                ('eula', models.TextField()),
                ('strings', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'db_table': 'edubox_languages',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
