# Generated by Django 3.1.7 on 2021-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200510_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
